(define n (read))
(define _lcm (read))
(define next 0)
(define a 0)
(define b 0)
(define myGcd 0)

(do ((i 1 (+ i 1)))
    ((> i n))
  (set! next (read))
  (set! a _lcm)
  (set! b next)
  
  (do ((temp b))
      ((eqv? b 0))
    (set! b (modulo a b))
    (set! a temp))
  (set! myGcd a)
  (set! _lcm (* _lcm (quotient next myGcd))))
(write _lcm)
