(define n (read))
(define _lcm (read))
(define next 0)
(define a 0)
(define b 0)
(define temp 0)
(define myGcd 0)

(do ((i 1 (+ i 1))
     (next (read))
     (a _lcm)
     (b next))
    ((< i n))
  (if (not(eqv? b 0))
      (begin
        (set! temp b)
        (set! b (modulo a b))
        (set! a temp)
        (set! myGcd a)
        (set! _lcm (* _lcm (quotient next myGcd)))
        (write _lcm))))
(write _lcm)
